---
# tasks file for kirikae.apache

- name: Install required packages
  package:
    name:
      - httpd
    state: present

- name: Enable Apache service
  service:
    name: httpd
    enabled: true
    state: started
