---
# tasks file for kirikae.install_win_ad

- name: Install AD feature
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Setup the AD controller
  win_domain:
    dns_domain_name: "{{ ad_dns_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: dcpromo_result

- name: Reboot AD if required
  win_reboot:
  when: dcpromo_result['reboot_required']

- name: Find domain list
  win_shell: nltest /dclist:"{{ ad_dns_domain_name }}"
  register: domain_list

- name: Print domain list
  debug:
    var: domain_list
