---
# defaults file for kirikae.users_ad_domain
user_info:
  - name: 'james'
    firstname: 'James'
    surname: 'Jockey'
    password: 'redhat@123'
    group_name: 'dev'
    group_scope: 'domainlocal'
  - name: 'bill'
    firstname: 'Bill'
    surname: 'Gates'
    password: 'redhat@123'
    group_name: 'dev'
    group_scope: 'domainlocal'
  - name: 'mickey'
    firstname: 'Mickey'
    surname: 'Mouse'
    password: 'redhat@123'
    group_name: 'qa'
    group_scope: 'domainlocal'
  - name: 'donald'
    firstname: 'Donald'
    surname: 'Duck'
    password: 'redhat@123'
    group_name: 'qa'
    group_scope: 'domainlocal'
