---
# tasks file for kirikae.win_ssh

- name: Install SSH packages
  win_chocolatey:
    name: "{{ item['package_name'] }}"
    params: "{{ item['parameters'] }}"
    state: present
  loop: "{{ win_services }}"

- name: Restart the windows service
  win_service:
    name: "{{ item['service_name'] }}"
    state: started
  loop: "{{ win_services }}"

- name: Enable firewall for services
  win_firewall_rule:
    name: "{{ item['service_name'] }}"
    localport: "{{ item['local_port'] }}"
    protocol: "{{ item['protocol_name'] }}"
    action: allow
    direction: in
    state: present
    enabled: yes
  loop: "{{ win_services }}"
