---
# tasks file for kirikae.postgres

- name: Install the required packages
  package:
    name:
      - postgresql-server
    state: present

- name: Check for present postgres data
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgsql_stat

- name: Initialise Postgres
  command: postgresql-setup initdb
  when: not pgsql_stat.stat.exists
  notify:
    - enable postgres
    - start postgres
